# Generated by Django 6.0 on 2025-12-17 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alunos', '0001_initial'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ATIVO', 'ativo'), ('TRANCADO', 'trancado'), ('CONCLUIDO', 'concluido')], default='ATIVO', max_length=20)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='alunos.aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='cursos.curso')),
            ],
            options={
                'unique_together': {('aluno', 'curso')},
            },
        ),
    ]
