# Generated by Django 6.0 on 2025-12-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
        ('cursos', '0001_initial'),
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('aluno', 'curso'), name='unique_aluno_curso'),
        ),
    ]
