# Generated by Django 6.0 on 2025-12-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='Professor',
            new_name='professor',
        ),
    ]
